# Generated by Django 3.1.1 on 2020-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='texttoimage')),
            ],
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
